In [1]:
import numpy as np 

In [2]:
a=np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [5]:
a=np.array([10,20,40,5])
a

array([10, 20, 40,  5])

In [6]:
#cerating a numpy with 5 values
a=np.array([1,2,3,4,5,])
a

array([1, 2, 3, 4, 5])

In [7]:
#cerating a numpy with 10 values
b=np.array([1,2,3,4,5,6,7,8,9,10])
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
b.shape

(10,)

In [9]:
a.shape

(5,)

In [10]:
a.ndim

1

In [11]:
b.ndim

1

In [12]:
d=np.array([[1,2,3],[4,5,6,]])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
d.shape

(2, 3)

In [14]:
d.ndim

2

In [15]:
e=np.array([[1,2,3,4,5],[6,7,8,9,10]])
e

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
e.shape

(2, 5)

In [17]:
e.ndim

2

In [19]:
e.dtype

dtype('int64')

In [20]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
b[2]   #indexind

np.int64(3)

In [29]:
b[2:6]  #slicing

array([3, 4, 5, 6])

In [30]:
c=np.array([6,7,8,9,10])
c

array([ 6,  7,  8,  9, 10])

In [32]:
#addition
a+c

array([ 7,  9, 11, 13, 15])

In [36]:
# substations 
a-c

array([-5, -5, -5, -5, -5])

In [34]:
#Division
a/c

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [35]:
#multiplication 
a*c

array([ 6, 14, 24, 36, 50])

In [38]:
np.sqrt(c)

array([2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [39]:
#exponential (2.718**)
np.exp(c)

array([  403.42879349,  1096.63315843,  2980.95798704,  8103.08392758,
       22026.46579481])

In [41]:
2.718**5

148.33623849186557

In [48]:
#arangeing
x=np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
x.ndim

1

In [50]:
x.shape

(12,)

In [51]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [52]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04])

In [53]:
x.dtype

dtype('int64')

In [54]:
#reshape
y=x.reshape((3,4))
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
y.shape

(3, 4)

In [56]:
y.ndim

2

In [57]:
y.dtype

dtype('int64')

In [59]:
np.exp(y)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [60]:
np.sqrt(y)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479]])